import msdfJSON from "../web/src/client/fonts/space-mono-regular-msdf/space-mono-regular-msdf.json";
import fs from "fs";

// function toZigLiteral(value) {
//   if (value === null) return "null";
//   if (value === undefined) return "undefined";

//   if (Array.isArray(value)) {
//     if (value.length === 0) return "&[_]void{}";
//     const items = value.map((item) => toZigLiteral(item)).join(", ");
//     return `&[_]${typeof value[0] === "string" ? "[]const u8" : "void"}{${items}}`;
//   }

//   if (typeof value === "string") {
//     return `"${value}"`;
//   }

//   if (typeof value === "number") {
//     if (value < 0) return value.toString();
//     return value.toString();
//   }

//   if (typeof value === "object") {
//     const entries = Object.entries(value)
//       .map(([key, val]) => `.${getKey(key)} = ${toZigLiteral(val)}`)
//       .join(",\n    ");
//     return `{\n    ${entries}\n}`;
//   }

//   return value.toString();
// }
//
const indent = "    ";
const getIndent = (depth) => indent.repeat(depth);

function generateZigStruct(json) {
  // First generate the type definitions
  let output = `// Auto-generated by gen-msdf.js, do not edit
const Font = struct {
    pages: []const []const u8,
    chars: []const Char,
    info: Info,
    common: Common,
    distance_field: DistanceField,
    kernings: []const void,
};

const Char = struct {
    id: u32,
    index: u32,
    char: []const u8,
    width: u32,
    height: u32,
    xoffset: i32,
    yoffset: u32,
    xadvance: u32,
    chnl: u32,
    x: u32,
    y: u32,
    page: u32,
};

const Info = struct {
    face: []const u8,
    size: u32,
    bold: u32,
    italic: u32,
    charset: []const []const u8,
    unicode: u32,
    stretch_h: u32,
    smooth: u32,
    aa: u32,
    padding: [4]u32,
    spacing: [2]u32,
};

const Common = struct {
    line_height: u32,
    base: u32,
    scale_w: u32,
    scale_h: u32,
    pages: u32,
    packed_: u32,
    alpha_chnl: u32,
    red_chnl: u32,
    green_chnl: u32,
    blue_chnl: u32,
};

const DistanceField = struct {
    field_type: []const u8,
    distance_range: u32,
};

`;

  // Then generate the data
  output += `pub const font = Font {\n`;
  output += `    .pages = .{\n`;
  for (const page of msdfJSON.pages) {
    output += `${getIndent(2)}"${page}",\n`;
  }
  output += `    },\n`;

  output += getIndent(1) + ".chars = .{\n";
  for (const char of msdfJSON.chars) {
    output += getIndent(2) + ".{\n";
    output += getIndent(3) + `.id = ${char.id},\n`;
    output += getIndent(3) + `.index = ${char.index},\n`;
    output += getIndent(3) + `.char = .{${JSON.stringify(char.char)}},\n`;
    output += getIndent(3) + `.width = ${char.width},\n`;
    output += getIndent(3) + `.height = ${char.height},\n`;
    output += getIndent(3) + `.xoffset = ${char.xoffset},\n`;
    output += getIndent(3) + `.yoffset = ${char.yoffset},\n`;
    output += getIndent(3) + `.xadvance = ${char.xadvance},\n`;
    output += getIndent(3) + `.chnl = ${char.chnl},\n`;
    output += getIndent(3) + `.x = ${char.x},\n`;
    output += getIndent(3) + `.y = ${char.y},\n`;
    output += getIndent(3) + `.page = ${char.page},\n`;
    output += getIndent(2) + `},\n`;
  }
  output += getIndent(1) + "},\n";
  output += getIndent(1) + ".info = .{\n";
  output += getIndent(2) + `.face = ${JSON.stringify(msdfJSON.info.face)},\n`;
  output += getIndent(2) + `.size = ${msdfJSON.info.size},\n`;
  output += getIndent(2) + `.bold = ${msdfJSON.info.bold},\n`;
  output += getIndent(2) + `.italic = ${msdfJSON.info.italic},\n`;
  output +=
    getIndent(2) +
    `.charset = .{ ${msdfJSON.info.charset.map((ch) => JSON.stringify(ch)).join(", ")} },\n`;
  output += getIndent(2) + `.unicode = ${msdfJSON.info.unicode},\n`;
  output += getIndent(2) + `.stretch_h = ${msdfJSON.info.stretchH},\n`;
  output += getIndent(2) + `.smooth = ${msdfJSON.info.smooth},\n`;
  output += getIndent(2) + `.aa = ${msdfJSON.info.aa},\n`;
  output +=
    getIndent(2) +
    `.padding = .{ ${msdfJSON.info.padding.map((p) => p).join(", ")} },\n`;
  output +=
    getIndent(2) +
    `.spacing = .{ ${msdfJSON.info.spacing.map((s) => s).join(", ")} },\n`;
  output += getIndent(1) + "},\n";

  output += getIndent(1) + `.common = .{\n`;
  output += getIndent(2) + `.line_height = ${msdfJSON.common.lineHeight},\n`;
  output += getIndent(2) + `.base = ${msdfJSON.common.base},\n`;
  output += getIndent(2) + `.scale_w = ${msdfJSON.common.scaleW},\n`;
  output += getIndent(2) + `.scale_h = ${msdfJSON.common.scaleH},\n`;
  output += getIndent(2) + `.pages = ${msdfJSON.common.pages},\n`;
  // packed is zig keyword
  output += getIndent(2) + `.packed_ = ${msdfJSON.common.packed},\n`;
  output += getIndent(2) + `.alpha_ch = ${msdfJSON.common.alphaChnl},\n`;
  output += getIndent(2) + `.red_ch = ${msdfJSON.common.redChnl},\n`;
  output += getIndent(2) + `.green_ch = ${msdfJSON.common.greenChnl},\n`;
  output += getIndent(2) + `.blue_ch = ${msdfJSON.common.blueChnl},\n`;
  output += getIndent(1) + "},\n";

  output += getIndent(1) + `.distance_field = .{\n`;
  output +=
    getIndent(2) +
    `.field_type = ${JSON.stringify(msdfJSON.distanceField.fieldType)},\n`;
  output +=
    getIndent(2) +
    `.distance_range = ${msdfJSON.distanceField.distanceRange},\n`;
  output += getIndent(1) + "},\n";

  output += `};`;

  return output;
}

// Generate the Zig code
const zigCode = generateZigStruct();

// Write to a file
fs.writeFileSync("core/src/render/fonts/space-mono-regular/msdf.zig", zigCode);
